version:  '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DAYABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mi-network
    ports:
      - "3307:3307"

  backend:
    build: .
    container_name: backend
    command: node index.js
    depends_on:
      - db
    networks:
      - mi-network
    ports:
      - "3000-3000"

networks:
  mi-network:
    driver: bridge

